const LISTA_ARGOMENTI = {
  ITALIANO: [
    "MARINETTI",
    "UNGARETTI",
    "PASCOLI",
    "GABRIELE D'ANNUNZIO",
    "VERGA",
    "EMILE ZOLA",
    "PIRANDELLO",
    "SABA",
    "FUTURISMO",
    "ITALO SVEVO",
    "DORIAN GRAY",
  ] as const,
  STORIA: [
    "SECONDA RIVOLUZIONE INDUSTRIALE",
    "FASCISMO",
    "USA",
    "UNITA D'ITALIA",
    "ETA GIOLITTIANA",
    "RIVOLUZIONE RUSSA",
    "NAZISMO",
    "PRIMA GUERRA MONDIALE",
  ] as const,
  MATEMATICA: [
    "CURVA DI KEELING",
    "CURVA DI WIDMARK",
    "CRESCITA POPOLAZIONE BATTERI",
    "SOMMINISTRAZIONE DI UN FARMACO NEL SANGUE",
    "FORMULA NUMERI GIRI G96 DEL TORNIO",
    "DERIVATA PRIMA=VELOCITA, DERIVATA SECONDA=ACCELERAZIONE",
  ] as const,
  INGLESE: [
    "FONTI RINNOVABILI E NON RINNOVABILI",
    "RISK",
    "METALLI FERRORI E NON FERROSI",
    "MANUFACTURING OPERATIONS",
    "COKETOWN",
    "CAD",
  ] as const,
  MECCANICA: [
    "ADDITIVE MANUFACTURING",
    "TRATTAMENTI TERMICI",
    "GESTIONE DELLA PRODUZIONE",
    "STATISTICA",
    "TIPOLOGIA PLACCHETTE UTENSILI",
    "STORIA DELLA QUALITA",
  ] as const,
  MOTORIA: [
    "COSTRUZIONE STADIO QATAR 2022",
    "SICUREZZA",
    "ALIMENTAZIONE",
    "SISTEMA CARDIOCIRCOLATORIO",
    "PARTITA DI CALCIO DEL NATALE 1914",
    "OLIMPIADI BERLINO DEL '36",
  ] as const,
  EDUCAZIONE_CIVICA: [
    "AGENDA 2030",
    "RICICLO ALLUMINIO",
    "RAEE",
    "ARTICOLO 1 COSTITUZIONE ITALIANA",
    "DONNE NEL LAVORO DURANTE LA 1°GUERRA MONDIALE",
    "ARTICOLO 9 COSTITUZIONE ITALIANA",
  ] as const,
};

const LISTA_NUCLEI_TEMATICI = [
  "AMBIENTE E ENERGIA",
  "SALUTE E SICUREZZA",
  "LAVORO, INDUSTRIA E INNOVAZIONE",
  "TEMPO",
] as const;

export { LISTA_ARGOMENTI, LISTA_NUCLEI_TEMATICI };
