<script lang="ts">
  const LISTA_ARGOMENTI = {
    ITALIANO: ["MARINETTI", "UNGARETTI", "PASCOLI", "GABRIELE D'ANNUNZIO", "VERGA", "EMILE ZOLA", "PIRANDELLO", "SABA", "FUTURISMO", "ITALO SVEVO", "DORIAN GRAY"] as const,
    STORIA: [
      "SECONDA RIVOLUZIONE INDUSTRIALE",
      "FASCISMO",
      "USA",
      "UNITA D'ITALIA",
      "ETA GIOLITTIANA",
      "RIVOLUZIONE RUSSA",
      "NAZISMO",
      "PRIMA GUERRA MONDIALE",
    ] as const,
    MATEMATICA: ["CURVA DI KEELING"] as const,
    INGLESE: ["FONTI RINNOVABILI E NON RINNOVABILI"] as const,
    MECCANICA: ["ADDITIVE MANUFACTURING", "TRATTAMENTI TERMICI"] as const,
    MOTORIA: ["COSTRUZIONE STADIO QATAR 2022"] as const,
    EDUCAZIONE_CIVICA: ["AGENDA 2030", "RICICLO ALLUMINIO", "RAEE"] as const,
  };
  const LISTA_NUCLEI_TEMATICHE = ["AMBIENTE E ENERGIA", "SALUTE E SICUREZZA", "LAVORO, INDUSTRIA E INNOVAZIONE", "TEMPO"] as const;

  type TypeMaterie = keyof typeof LISTA_ARGOMENTI;
  type TypeArgomenti<TypeThisMateria extends TypeMaterie> = typeof LISTA_ARGOMENTI[TypeThisMateria][number];
  type TypeNucleiTematici = typeof LISTA_NUCLEI_TEMATICHE[number];
</script>
