<script lang="ts">
  const LISTA_ARGOMENTI = {
    ITALIANO: ["MARINETTI", "UNGARETTI", "PASCOLI", "GABRIELE D'ANNUNZIO"],
    STORIA: [
      "SECONDA RIVOLUZIONE INDUSTRIALE",
      "FASCISMO",
      "CROLLO DELLA BORSA DI WALL STREET",
    ],
  };
</script>
